name: color-palettes-app

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'config/**'
      - 'public/**'
      - 'package.json'
      - '.github/workflows/**'
      - '.husky/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x] # Specify the node version or versions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use latest npm
        run: npm install -g npm@latest

      # Cache dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Clear package-lock.json and node_modules
      - name: Clear package-lock.json and node_modules
        run: |
          rm -rf package-lock.json node_modules
          npm install

      - name: Run Linter
        run: npm run lint
      
      - name: Run Jest Tests
        run: npm run test
      
      - name: Build
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/
